include: package:flutter_lints/flutter.yaml
linter:
  rules:
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_void_async: true
    cancel_subscriptions: true
    secure_pubspec_urls: false
    sort_constructors_first: true
    unnecessary_lambdas: true
    unnecessary_await_in_return: true
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_named_constants: true
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
